# Generated by Django 2.1.3 on 2018-11-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['consumption_date', 'consumption_time']},
        ),
    ]
