# Generated by Django 2.1.3 on 2018-11-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumed', '0002_auto_20181129_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='alcohol_content',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='drink',
            name='volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
