# Generated by Django 2.1.3 on 2018-11-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumed', '0003_auto_20181129_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='alcohol_content',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='drink',
            name='volume',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
