# Generated by Django 2.1.3 on 2018-11-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumed', '0004_auto_20181129_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
