# Generated by Django 2.1.3 on 2018-11-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumed', '0005_drink_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='alcohol_content',
            field=models.DecimalField(decimal_places=1, default=0, help_text='This is half the proof', max_digits=4),
        ),
    ]
