# Generated by Django 2.1.3 on 2018-12-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumed', '0006_auto_20181129_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drink',
            name='volume',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Ounces of drink', max_digits=4),
        ),
    ]
