# Generated by Django 2.1.3 on 2018-12-06 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumed', '0007_auto_20181202_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='alcohol_content',
            field=models.DecimalField(decimal_places=1, help_text='This is half the proof', max_digits=4),
        ),
        migrations.AlterField(
            model_name='drink',
            name='volume',
            field=models.DecimalField(decimal_places=1, help_text='Ounces of drink', max_digits=4),
        ),
    ]
