# Generated by Django 2.1.3 on 2018-12-06 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumed', '0008_auto_20181205_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='author',
            new_name='created_by',
        ),
    ]
